const pappardelle = function (e) {
  e.preventDefault();
  const form = document.getElementById("form");
  const newTask = document.querySelector("#enterIt");
  const p = document.createElement("p");
  const nuovoTask = newTask.value;
  p.classList.add("nuovoTask");
  console.log("'", nuovoTask, "'  è stato aggiunto alla lista");
  p.innerText = `${nuovoTask}`;
  const cestino = document.createElement("button");
  cestino.innerHTML += "<img src='./cestino.png'/>";
  const check = document.createElement("button");
  check.innerHTML += "<img src='./check.png'>";
  const riga = document.createElement("div");
  riga.appendChild(cestino);
  riga.appendChild(p);
  riga.appendChild(check);
  riga.classList.add("riga");
  const list = document.getElementById("list");
  list.appendChild(riga);
  form.reset();
};
